name: 2. AKS in GH Actions

on:
  push:
    branches: [ main ]
    paths: 
    - 2.AKS_in_GH_actions/**
    - .github/workflows/2_aks_in_GH_actions.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2.AKS_in_GH_actions
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out plan.out -var resource_group_name=devnetwork-ask-$(echo ${GITHUB_SHA} | cut -c1-6)
        
      - name: Terraform apply
        run: terraform apply plan.out
