name: 4. Self Destruct cluster

on:
  push:
    branches: [ main ]
    paths:
    - 4.Self_destructing_cluster**
    - .github/workflows/4.self_destructing_AKS.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4.Self_destructing_cluster
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out plan.out -var resource_group_name=devnetwork-aks-$(echo ${GITHUB_SHA} | cut -c1-6)

      - name: Terraform apply
        run: terraform apply plan.out
      
      - name: Get kubeconfig
        run: terraform output kubeconfig > kubeconfig
        
      - name: Get clientID
        run: echo "CLIENTID=$(terraform output clientid)" >> $GITHUB_ENV
        
      - name: echo clientID
        run: echo ${{ env.CLIENTID }}

      - name: Create configmap
        run: kubectl create --kubeconfig ./kubeconfig configmap az-config --from-literal=rgname=devnetwork-aks-$(echo ${GITHUB_SHA} | cut -c1-6) --from-literal=clientid=${{ env.CLIENTID }}
        
      - name: Create delete job
        run: kubectl create --kubeconfig ./kubeconfig -f job.yaml
